### PR TITLE
Sync client

### PR DESCRIPTION
**Pull request by cmleinz**
Currently if the library is compiled without the default async client feature, it will fail. This PR aims to resolve that issue, as well as provide a sync client as an alternative to the async version. Currently these changes aren't fully tested (and currently are non functional for the sync client). But I wanted to put this out so others could weigh in.

### CODE REVIEW

**Comment by arnstein** [comment]
Hey, sorry for the late reply! I have been on vacation.
It is a bit hectic getting back to work right now, but I will check it out ASAP and get back to you. Thanks for this :)

**Comment by cmleinz** [comment]
No problem! This PR is not quite ready for merging I haven't had the time just yet to properly finalize the changes, but I may have time in the next few days 🙂

**Comment by arnstein** [comment]
I like what I see so far! When you think it is ready to merge I will give it a spin and if it seems to work well we can merge it and prepare for a new release :)

**Comment by arnstein** [comment]
Greetings,
just curious: any updates on this?

**Comment by cmleinz** [comment]
Hi! Sorry, been busy with work. I'll try to take a look this weekend

**Comment by cmleinz** [comment]
Thanks for your patience, the changes should be complete now pending your approval

**Comment by arnstein** [comment]
How busy our work is seems to be perfectly out of phase! But I will test it out ASAP. Thanks a lot for this contribution!

**Comment by arnstein** [comment]
This seems to work well in my tests. Thank you very much :100:

**Pull request merged**
